spring:
  application:
    name: springbootZuul
server:
  port: 8001
eureka:
  client:
    service-url:
        defaultZone : http://localhost:5000/eureka/
zuul:
  routes:
    sbService :
      path: /sbService/**
      serviceId : springbootService
